#!/bin/sh
set -eu

# Applies pending Prisma migrations against DATABASE_URL/DIRECT_URL, then
# starts the Remix production server. Run from apps/builder (see Dockerfile).
#
# The root "migrations" script (see /app/package.json) passes --dev and
# --cwd but no subcommand - it must be invoked with an explicit "migrate"
# argument, which pnpm forwards to packages/prisma-client/migrations-cli.
cd /app
pnpm run migrations migrate

cd /app/apps/builder

# vite.config.ts applies @vercel/remix's vercelPreset() unconditionally, so
# `remix vite:build` always emits Vercel-style server bundles under
# build/server/<runtime-id>/index.js instead of the plain build/server/
# index.js the package.json "start" script (remix-serve build/server/
# index.js) assumes. Locate the actual entry instead of hardcoding the
# runtime-id directory name, which is generated by preset internals.
SERVER_ENTRY=$(find build/server -maxdepth 2 -name index.js | head -n1)
if [ -z "$SERVER_ENTRY" ]; then
  echo "No build/server/**/index.js found - build output layout changed?" >&2
  exit 1
fi

# Use our own Express server instead of remix-serve: remix-serve never enables
# Express's "trust proxy", so req.protocol stayed "http" behind Traefik's TLS
# termination and Webstudio's own OAuth rejected the resulting http://
# redirect_uri when opening a project. See apps/builder/server.mjs.
export SERVER_BUILD_PATH="$PWD/$SERVER_ENTRY"
exec node server.mjs
